#
# CI-CD Pipeline fÃ¼r das PSE Matrix-basierte Micropayments
#

name: CI/CD Pipeline on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

  env:
    NODE_VERSION: 20

  jobs:
    #
    # Build Stage
    #

  install-npm-dependencies:
    name: Install npm dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

  build-review:
    name: Build (Review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Patch Vite base path
        run: |
          echo "REF_SLUG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          sed -i "s#base: '/'#base: '/$REF_SLUG/'#g" vite.config.ts
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-review
          path: dist/

  test:
    uses: ./.github/workflows/test-stage.yml
    with:
      node-version: 20
