#
# Test Stage
#
name: Test Stage

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-npm-dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
      - name: Install dependencies
        run: npm ci
      - run: npm run lint-check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: install-npm-dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
      - name: Install dependencies
        run: npm ci
      - run: npm run format-check

  cypress:
    name: Cypress E2E
    runs-on: ubuntu-latest
    needs: install-npm-dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
      - name: Install dependencies
        run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          background: true
        env:
          CYPRESS_TEST_ACCOUNTS: ${{ secrets.TEST_ACCOUNTS }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-artifacts
          path: |
            coverage
            cypress/videos
            cypress/screenshots
